### ISSUE TITLE
Memory Leakage issues

### ISSUE THREAD

**Issue by abdulrehmanveemed** [DeepARSDK/vonage-ios-swift#2]
So I am using deepar with vonage and as soon I start deepAR camera, memory leakage starts. Memory going upto 600-900MB after disabling deepAR memory goes down to 180mb.

**Comment by JelenaKB** [comment]
We could not reproduce this issue. Could you please provide us with additional info? What If any changes have you done to the example code? Which iOS and SDK versions this issue was present on?
